---
version: "2.0"

services:
  intentjournal-app:
    image: ghcr.io/toxmon/intentjournal-plus:7aca572
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
    env:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NEXT_TELEMETRY_DISABLED=1
      - GENERATE_SOURCEMAP=false
      - NEXT_PUBLIC_BASE_SEPOLIA_RPC=https://sepolia.base.org
      - NEXT_PUBLIC_ETHERLINK_RPC=https://node.ghostnet.etherlink.com

profiles:
  compute:
    intentjournal-app:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          - size: 2Gi
  placement:
    akash:
      pricing:
        intentjournal-app:
          denom: uact
          amount: 1000

deployment:
  intentjournal-app:
    akash:
      profile: intentjournal-app
      count: 1
